# example full configuration from dev branch
# devices Atom S3 Lite + tail485

substitutions:
  device_name: olea103

external_components:
  - source:
      type: git
      url: https://github.com/tesu84/esphome-sauna360/
      ref: develop
    components: [ sauna360 ]

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  comment: ${device_name} sauna controller
  area: Sauna

esp32:
  #change right board for your device
  board: esp32-s3-devkitc-1

# Enable logging
logger:
  level: DEBUG
  # disable putting logging on the HW uart
  baud_rate: 0

# Enable Home Assistant API
api:

# Enable OTA updates and read logs with wifi
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

uart:
    # change right pins for your ESPhome device
    rx_pin: GPIO1
    tx_pin: GPIO2
    baud_rate: 19200
    data_bits: 8
    parity: EVEN
    stop_bits: 1

sauna360:
  #flow_control_pin: GPIO7 #PIN to set transmit DE ~RE pins high on RS485 board

binary_sensor:
- platform: sauna360
  heater_status:
    name: "Heater Status"
- platform: sauna360
  light_status:
    name: "Light Status"
- platform: sauna360
  ready_status: 
    name: "Ready Status"
- platform: sauna360
  relay_x3_x4_status: 
    name: "Relay X3-X4 Status"
- platform: sauna360
  relay_x5_x6_status: 
    name: "Relay X5-X6 Status"
- platform: sauna360
  relay_x7_x8_status: 
    name: "Relay X7-X8 Status"
- platform: sauna360
  relay_x9_x10_status: 
    name: "Relay X9-X10 Status"
- platform: sauna360
  relay_x11_x12_status: 
    name: "Relay X11-X12 Status"
- platform: sauna360
  relay_x13_x14_status: 
    name: "Relay X13-X14 Status"
- platform: sauna360
  relay_x15_x16_status: 
    name: "Relay X15-X16 Status"
- platform: sauna360
  relay_x17_x18_status: 
    name: "Relay X17-X18 Status"

sensor:
- platform: wifi_signal
  name: "${device_name} WiFi Signal"
  update_interval: 60s
  icon: "mdi:wifi"
- platform: sauna360
  current_temperature:
    name: "Current Temperature"
- platform: sauna360
  setting_temperature:
    name: "Setting Temperature"
- platform: sauna360
  remaining_time:
    name: "Remaining Time"
- platform: sauna360
  setting_bath_time:
    name: "Setting Bath Time"
- platform: sauna360
  humidity_setting: #combi/steam pure models 1-10
    name: "Sensor Setting Humidity Step"
- platform: sauna360
  humidity_percentage_setting: #combi/steam elite models with Rh% Sensor
    name: "Sensor Setting Humidity Percentage"
- platform: sauna360
  humidity_percentage: #combi/steam elite models with Rh% Sensor
- platform: sauna360
  humidity_percentage:
    name: "Humidity"
- platform: sauna360
  total_uptime:
    name: "Total Uptime"
- platform: sauna360
  max_bath_temperature:
    name: "Max Bath Temperature"
- platform: sauna360
  overheating_pcb_limit:
    name: "Overheating PCB Limit"
- platform: sauna360
  standby_temperature_reduction:
    name: "Standby Temperature Reduction"
- platform: sauna360
  external_switch_renew_bathtime:
    name: "External Switch Renew Bathtime"

button:
- platform: sauna360
  heater_on:
    name: "On"
- platform: sauna360
  heater_off:
    name: "Off "
- platform: sauna360
  heater_standby:
    name: "Standby"
- platform: sauna360
  heater_power_toggle:
    name: "Power Toggle"

number:
- platform: sauna360
  bath_time:
    name: "Bath Time"
    mode: box # box / slider
    bath_time_default: 90 #1-360min
- platform: sauna360
  bath_temperature:
    name: "Bath Temperature"
    mode: box # box / slider
    bath_temperature_default: 65 #40-110°C
- platform: sauna360
  standby_temperature_reduction:
    name: "Standby Temperature Reduction"
    mode: box # box / slider
    standby_temperature_reduction_default: 30 #0-30°C
- platform: sauna360
  humidity_step:
    name: "Humidity Step Setting"
    mode: box # box / slider
    humidity_step_default: 2 #0-10
- platform: sauna360
  humidity_percentage:
    name: "Number Humidity percentage Setting"
    mode: box # box / slider
    humidity_percentage_default: 10 #0-70%
- platform: sauna360
  max_bath_temperature:
    name: "Max Bath Temperature"
    mode: box # box / slider
    max_bath_temperature_default: 90 #40-110°C
- platform: sauna360
  overheating_pcb_limit:
    name: "Overheating PCB Limit"
    mode: box # box / slider
    overheating_pcb_limit_default: 80 #70-90°C
- platform: sauna360
  external_switch_renew_bathtime:
    name: "External Switch Renew Bath Time"
    mode: box # box / slider
    external_switch_renew_bathtime_default: 90 #1-360min
- platform: sauna360
  aux0_fragrance_pump:
    name: "Aux0 Fragrance Pump"
    mode: box # box / slider
    aux0_fragrance_pump_default: 10 #1-1200*100ms 10=1s
- platform: sauna360
  aux0_fragrance_stop:
    name: "Aux0 Fragrance Stop"
    mode: box # box / slider
    aux0_fragrance_stop_default: 10 #1-7200s
- platform: sauna360
  aux1_fragrance_pump:
    name: "Aux1 Fragrance Pump"
    mode: box # box / slider
    aux1_fragrance_pump_default: 10 #1-1200*100ms 10=1s
- platform: sauna360
  aux1_fragrance_stop:
    name: "Aux1 Fragrance Stop"
    mode: box # box / slider
    aux1_fragrance_stop_default: 10 #1-7200s
- platform: sauna360
  aux2_fragrance_pump:
    name: "Aux2 Fragrance Pump"
    mode: box # box / slider
    aux2_fragrance_pump_default: 10 #1-1200*100ms 10=1s
- platform: sauna360
  aux2_fragrance_stop:
    name: "Aux2 Fragrance Stop"
    mode: box # box / slider
    aux2_fragrance_stop_default: 10 #1-7200s

switch:
- platform: sauna360
  light_relay:
    name: "Light"
- platform: sauna360
  aux0_relay:
    name: "Aux 0" #Relay X15-X16
- platform: sauna360
  aux1_relay:
    name: "Aux 1" #Relay X11-X12
- platform: sauna360
  aux2_relay:
    name: "Aux 2"
- platform: sauna360
  standby_enable:
    name: "Standby Enable"
- platform: sauna360
  activate_time_limit:
    name: "Activate Time Limit"

select:
- platform: sauna360
  relay_aux0_mode:
    name: "Relay Aux0 Mode"
- platform: sauna360
  relay_aux1_mode:
    name: "Relay Aux1 Mode"
- platform: sauna360
  relay_aux2_mode:
    name: "Relay Aux2 Mode"
- platform: sauna360
  external_switching_mode:
    name: "External Switch Mode"
- platform: sauna360
  bath_type_priority:
    name: "Bath Type Priority"
- platform: sauna360
  facility_type:
    name: "Facility Type"

text_sensor:
- platform: sauna360
  heater_state:
    name: "Heater State"
- platform: sauna360
  water_level:
    name: "Water Level"

time:
  - platform: homeassistant

datetime:
- platform: sauna360
  name: "Datetime"
  not_allowed_start_from:
    name: "Not Allowed Start From"
  not_allowed_start_until:
    name: "Not Allowed Start Until"